project 'iGithub.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iGithub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iGithub
  pod 'RxMoya'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'HandyJSON'

  target 'iGithubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iGithubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
